language: node_js
sudo: required
addons:
  apt:
    packages:
      - xvfb
node_js:
- 5.5.0
install:
- export DISPLAY=':99.0'
- Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
- npm install
script:
- npm test
- ls temp
after_success:
- npm run after_success
